repos:
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: ["--config=./.flake8"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: run-pytest
        name: Run unit tests
        entry: python -m pytest
        args: ["-q", "./src/tests/"]
        language: python
        additional_dependencies:
          - pytest
          - pytest-asyncio
          - requests
          - pydantic
          - langgraph
          - fastapi
          - sse_starlette
          - dotenv
          - langgraph-checkpoint-postgres
          - langchain_openai
          - pydantic_settings
          - google-cloud-aiplatform
          - google-cloud-discoveryengine
          - psycopg[binary]
          - a2a-sdk
          - langfuse
        pass_filenames: false
        always_run: true
